### ISSUE TITLE
Constant error in events.js

### ISSUE THREAD

**Issue by stopsatgreen** [cssnext/gulp-cssnext#4]
Have installed the latest version, set up my gulpfile.js, but when I run the task I get this error:

```
events.js:85
      throw er; // Unhandled 'error' event
            ^
TypeError: undefined is not a function
    at LazyResult.run (/Users/petergasston/Sites/prototypes/mucking-about/cssnext/node_modules/gulp-cssnext/node_modules/cssnext/node_modules/postcss/lib/lazy-result.js:193:24)
    at LazyResult.sync (/Users/petergasston/Sites/prototypes/mucking-about/cssnext/node_modules/gulp-cssnext/node_modules/cssnext/node_modules/postcss/lib/lazy-result.js:179:32)
    at LazyResult.stringify (/Users/petergasston/Sites/prototypes/mucking-about/cssnext/node_modules/gulp-cssnext/node_modules/cssnext/node_modules/postcss/lib/lazy-result.js:210:14)
    at LazyResult._createClass.get (/Users/petergasston/Sites/prototypes/mucking-about/cssnext/node_modules/gulp-cssnext/node_modules/cssnext/node_modules/postcss/lib/lazy-result.js:232:25)
    at cssnext (/Users/petergasston/Sites/prototypes/mucking-about/cssnext/node_modules/gulp-cssnext/node_modules/cssnext/index.js:220:20)
    at DestroyableTransform._transform (/Users/petergasston/Sites/prototypes/mucking-about/cssnext/node_modules/gulp-cssnext/index.js:24:23)
    at DestroyableTransform.Transform._read (/Users/petergasston/Sites/prototypes/mucking-about/cssnext/node_modules/gulp-cssnext/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/Users/petergasston/Sites/prototypes/mucking-about/cssnext/node_modules/gulp-cssnext/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/Users/petergasston/Sites/prototypes/mucking-about/cssnext/node_modules/gulp-cssnext/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/Users/petergasston/Sites/prototypes/mucking-about/cssnext/node_modules/gulp-cssnext/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:227:5)
```
Have checked my paths and run a ‘virgin’ pipeline, all works fine; the error is when `cssnext` is run.

**Comment by stopsatgreen** [comment]
My files, for reference: https://github.com/stopsatgreen/gulp-cssnext

**Comment by MoOx** [comment]
Seems related to https://github.com/cssnext/cssnext/issues/131

**Comment by stopsatgreen** [comment]
That seems right - disabled autoprefixer and it runs without problems.
```
features: {
  autoprefixer: false
}
```
